### ISSUE TITLE
Not able to run calculator_example.py file

### ISSUE THREAD

**Issue by rishavmitra** [anthropics/anthropic-tools#10]
Running the file throws the error

`line 7, in <module>
    from .tools.base_tool import BaseTool
ImportError: attempted relative import with no known parent package`.

Steps to reproduce:

1. Clone the repository
2. Run calculator_example.py inside tool_use_package

**Comment by nmarwell-anthropic** [comment]
Hi @rishavmitra! Sorry to hear you are running into issues. Could you please provide the command you are using to run this file, and where in the directory structure you are running it from?
